
name: Run PHPUnit Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug

      - name: Install dependencies
        run: composer install

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit --coverage-clover coverage.xml

      - name: Check coverage threshold
        run: |
          COVERAGE=$(php -r '
              $xml = simplexml_load_file("coverage.xml");
              $metrics = $xml->project->metrics;
              $coverage = ($metrics["coveredstatements"] / $metrics["statements"]) * 100;
              echo round($coverage, 2);
          ')
          echo "Coverage is $COVERAGE%"
          if (( $(echo "$COVERAGE < 75" | bc -l) )); then
              echo "Coverage must be at least 75%";
              exit 1;
          fi

      - name: Comment coverage in PR
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: coverage
          message: |
            📊 **Code Coverage**
            ```
            $COVERAGE%
            ```
